repo = "https://raw.githubusercontent.com/kumalum/config-singbox/rule-set"

[downloads]

microsoft = [
    "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-microsoft@cn.srs"
]

microsoft_cn = [
	"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-microsoft@cn.srs"
]

github = [
	"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-github.srs"
]

google_play = [
	"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google-play.srs"
]

cn = [
	"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs"
]

telegram = [
	"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-telegram.srs"
]

ads_all = [
	"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs"
]

# AdGuard 规则集直接转换为 srs 文件 无法转换为 json
adguard = ["https://raw.githubusercontent.com/ppfeufer/adguard-filter-list/refs/heads/master/blocklist"]

[program]

sing-box = 'sing-box'

[proxy]

flag = false
url = "127.0.0.1"
port = 10808