name: Generate sing-box config template
on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'
  
# 关键：在 workflow 级别设置权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh -s -- --version 1.12.12
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install requirements.txt
        run: | 
          pip install -r ./requirements.txt 
        
          # 执行更新程序
      - name: Run run.py
        run: python run.py

      - name: Push to config-singbox repo
        run: |

          # 克隆 config-singbox仓库
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/config-singbox.git
          cp -r 1.12.json config-singbox/1.12
          cd config-singbox

          # 设置用户以示区分
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          
          # 推送模板文件到 main/版本号中
          git add .
          git commit -m "update"
          git push

          # 推送源文件 到分支 rule-set
          git checkout rule-set
          cp ../rule-set/*.srs ./
          git add .
          git commit -m "update"