name: Generate sing-box config template
on: 
  push:
    branches:
      - main
    paths:
      - update-rule-set.py
  schedule:
    - cron: '0 5 * * *'
  
# 关键：在 workflow 级别设置权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh -s -- --version 1.12.12
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install requirements.txt
        run: | 
          pip install -r ./requirements.txt 
        
      - name: Run Python
        run: |
          python update-rule-set.py N


      - name: Push base/url_set.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"

          git add .
          git commit -m "update"
          git push

      - name: Push to config-singbox repo
        run: |

          # 克隆 config-singbox rule-set 分支的最新提交记录
          git clone --depth 1 -b rule-set https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/config-singbox.git
          
          ls rule-set
          cd config-singbox
          cp -r rule-set/*.srs config-singbox/

          # 设置用户以示区分
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"

          # 推送源文件 到分支 rule-set
          git add .
          git commit -m "update"
          git push