name: Generate sing-box rule-set
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - update-rule-set.py
      - base/pref_config.toml
  schedule:
    - cron: '0 8 * * 1'
  
# 关键：在 workflow 级别设置权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.9'
          cache: "pip"
      - run:
         pip install -r requirements.txt 

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh -s -- --version 1.12.12

      - name: Run Python
        run: |
          python update-rule-set.py N

      - name: Push to config-singbox repo
        run: |

          # 克隆 config-singbox rule-set 分支的最新提交记录
          git clone --depth 1 -b rule-set https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/config-singbox.git
          
          # 复制输出的 rule-set 文件到 config-singbox
          cp output/*.srs output/config/set_config.json config-singbox/
          cd config-singbox

          # 推送源文件 到分支 rule-set
          git add .
          git commit -m "update" || echo "nothing to commit"
          git push --force || echo "nothing to push"